### ISSUE TITLE
Convert from implicit hydrogens change layout

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1452]
After convert from implicit to explicit hydrogens molecule layout changed which is wrong.

Molecules shold keep position and forms.
New explicit hydrogens should be layouted only.

**Comment by AliaksandrDziarkach** [comment]
Fixed

**Comment by AlexeyGirin** [comment]
Not fixed.
https://github.com/epam/Indigo/assets/26869421/cad25de3-c377-4150-9770-632e26757832

**Comment by AliaksandrDziarkach** [comment]
This is ketcher issue.
Indigo got next data from ketcher:
```
{
    "root": {
        "nodes": [
            {
                "$ref": "mol0"
            }
        ],
        "connections": [],
        "templates": []
    },
    "mol0": {
        "type": "molecule",
        "atoms": [
            {
                "label": "C",
                "location": [
                    2.009849152128566,
                    -8.725074417174607,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    3.7401508478714343,
                    -8.724589229177203,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.876637509491239,
                    -8.224966888850187,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    3.7401508478714343,
                    -9.725532067822147,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.009849152128566,
                    -9.730020056798137,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.8788208554795585,
                    -10.225033111149813,
                    0
                ]
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            }
        ]
    }
}
```
And response with 
```
{
    "root": {
        "nodes": [
            {
                "$ref": "mol0"
            }
        ]
    },
    "mol0": {
        "type": "molecule",
        "atoms": [
            {
                "label": "C",
                "location": [
                    2.0098490715026857,
                    -8.725074768066407,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    3.7401509284973146,
                    -8.724589347839356,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.8766374588012697,
                    -8.224967002868653,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    3.7401509284973146,
                    -9.725532531738282,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.0098490715026857,
                    -9.730020523071289,
                    0
                ]
            },
            {
                "label": "C",
                "location": [
                    2.8788208961486818,
                    -10.225032806396485,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    1.1438956260681153,
                    -8.224949836730957,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    4.606409072875977,
                    -8.224992752075196,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    2.877246856689453,
                    -7.224967002868652,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    4.606656551361084,
                    -10.224699974060059,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    1.1452752351760865,
                    -10.232526779174805,
                    0
                ]
            },
            {
                "label": "H",
                "location": [
                    2.882678508758545,
                    -11.225025177001954,
                    0
                ]
            }
        ],
        "bonds": [
            {
                "type": 2,
                "atoms": [
                    2,
                    0
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    4
                ]
            },
            {
                "type": 2,
                "atoms": [
                    4,
                    5
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    3
                ]
            },
            {
                "type": 2,
                "atoms": [
                    3,
                    1
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    2
                ]
            },
            {
                "type": 1,
                "atoms": [
                    0,
                    6
                ]
            },
            {
                "type": 1,
                "atoms": [
                    1,
                    7
                ]
            },
            {
                "type": 1,
                "atoms": [
                    2,
                    8
                ]
            },
            {
                "type": 1,
                "atoms": [
                    3,
                    9
                ]
            },
            {
                "type": 1,
                "atoms": [
                    4,
                    10
                ]
            },
            {
                "type": 1,
                "atoms": [
                    5,
                    11
                ]
            }
        ]
    }
}
```
As you can see carbon coodinates didn't changed.

**Comment by AlexeyGirin** [comment]
Moved to KEtcher - https://github.com/epam/ketcher/issues/4040
